import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  #"~/.config/alacritty/catppuccin-latte.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",
]
[env]
TERM = "xterm-256color"
[font]
size = 16.0
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
[font.bold]
style = "Bold"
family = "Hack Nerd Font Mono"
[font.italic]
style = "Italic"
family = "Hack Nerd Font Mono"
[font.bold_italic]
family = "Hack Nerd Font Mono"
