[env]
TERM = "xterm-256color"
[font]
size = 14.0
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
[font.bold]
style = "Bold"
family = "Hack Nerd Font Mono"
[font.italic]
style = "Italic"
family = "Hack Nerd Font Mono"
[font.bold_italic]
family = "Hack Nerd Font Mono"
